title: Alberto Araujo
#logo: /assets/img/perfil.png.jpg
description: MBA USP/Esalq Data Science & Analytics e Data Scientist Student
description: LinkedIn
logo: /assets/icons/linkedin.svg
show_downloads: false
theme: jekyll-theme-minimal

# Redes Sociais
social:
  - name: LinkedIn
    url: https://www.linkedin.com/in/alberto-ferreira-araujo-352744b1
    icon: /assets/icons/linkedin.svg
  - name: GitHub
    url: https://github.com/AlbertoFAraujo
    icon: /assets/icons/github.svg
  # Adicione outras redes sociais aqui
